projects:
  database:
    schemaPath: ${env:PRISMA_SCHEMA_PATH}/schema.graphql
    includes:
      - ${env:PRISMA_SCHEMA_PATH}/seed.graphql
      - ${env:SHARED_SCHEMA_PATH}/enums.graphql
      - ${env:PRISMA_SCHEMA_PATH}/models/user.graphql
    extensions:
      prisma: prisma.yml
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: ${env:PRISMA_SCHEMA_PATH}/index.ts
