version: '3'
services:
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      name: ${REDIS_NAME}
      password: ${REDIS_PASS}
  prisma:
    image: prismagraphql/prisma:1.16
    restart: always
    depends_on:
      - postgres
    ports:
      - ${PRISMA_PORT}:${PRISMA_PORT}
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_PORT}
        databases:
          default:
            connector: postgres
            host: postgres
            port: ${POSTGRES_PORT}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASS}
            migrations: true
  postgres:
    image: postgres:10.5
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
