projects:
  app:
    schemaPath: ${env:APP_SCHEMA_PATH}/app.graphql
    includes:
      - ${env:APP_SCHEMA_PATH}/mutations/user-mutation.graphql
      - ${env:APP_SCHEMA_PATH}/auth-payload.graphql
      - ${env:APP_SCHEMA_PATH}/user.graphql
    extensions:
      endpoints:
        default: ${env:PRISMA_ENDPOINT}
      codegen:
      - generator: graphql-binding
        language: typescript
        output:
          binding: ${env:APP_SCHEMA_PATH}/index.ts

  database:
    schemaPath: ${env:PRISMA_SCHEMA_PATH}/schema.graphql
    includes:
      # - ../schemas/src/prisma/prisma.graphql
      - ${env:PRISMA_SCHEMA_PATH}/seed.graphql
      - ${env:PRISMA_SCHEMA_PATH}/models/user.graphql
    extensions:
      prisma: ./prisma.yml
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: ${env:PRISMA_SCHEMA_PATH}/index.ts
