apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /c/Users/marcus-sa/.minikube/ca.crt
    server: https://10.3.47.182:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /c/Users/marcus-sa/.minikube/client.crt
    client-key: /c/Users/marcus-sa/.minikube/client.key
